# Generated by Django 3.2.6 on 2021-08-30 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='plusmemo',
            field=models.TextField(default='', null=True),
        ),
    ]
